{% set name = "spatialgeometry" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialgeometry-{{ version }}.tar.gz
  sha256: b61268134dc9130fcc837817b352a5011081470a3002bc15482492176afd3789

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - spatialmath-python >=0.9.2

test:
  imports:
    - spatialgeometry
    - spatialgeometry.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jhavl/spatialgeometry
  summary: A Shape and Geometry Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
