{% set name = "spatialgeometry" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialgeometry-{{ version }}.tar.gz
  sha256: eb58809ffee529e7214a2dd63b96fb0f9e4aa41978cae720cb0d0cbcd170ab0a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - numpy
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - spatialmath-python >=1.0.0
    - numpy

test:
  imports:
    - spatialgeometry
    - spatialgeometry.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jhavl/spatialgeometry
  summary: A Shape and Geometry Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
